### PR TITLE
Adding landing page.

### LINKED ISSUE #40: Add a landing page?
I feel like we should have the logo and name of the school somewhere in the site (this has also been mentioned in some of the feedback i have recieved) so I thought of using a landing page like we have for the code club site (see pic below). What do you think?

image

### PR DESCRIPTION
**Pull request by AdamPohl**
This fixes #40 

I have added a landing page as I feel that there should be some way of telling what uni & subsecent school it was for. See pics below.

On desktop:
image

On mobile: 
image

### CODE REVIEW

**Comment by drvinceknight** [comment]
Not sure if this is necessary (adds an extra tiny level of complexity: 1 more click) _but_ if you do want to keep it the wording needs to be fixed:

"Select your degree scheme" is quite misleading, if someone just saw this webpage it looks very official and looks like it's actually what you use to officially select your degree scheme. You need to clarify that and possibly also state that (at present at least) this is a tool that can assist but should only be used as guidance as some of the data could be incorrect (or something like that).

**Comment by AdamPohl** [comment]
> Not sure if this is necessary

I have had a number of people say to me that they feel that the cardiff uni logo and name of school should be somewhere on the page. I felt the initial page was the best. 

> (adds an extra tiny level of complexity: 1 more click)

I don't think this matters much as the site is comprised of you pressing buttons.

> "Select your degree scheme" is quite misleading, 

I was not sure what to make it so I put this what would you suggest I change it to @drvinceknight ?

**Comment by drvinceknight** [comment]
I would change the 'select your degree scheme' to 'start' but I honestly
don't see why there is a need for a landing page (it's not in line with a
lot of modern ui trends), it tells me nothing and just delays me getting
started (as well as loading a bunch of bytes of image file). I hate it when
I go to a page it loads up and I just have to click on next (ie load the
actual page I wanted).

You could have the logo/school in small in a corner and this also deals
with my issue of it looking official (which unless there is a disclaimer,
at this point in time it should not).

**Comment by drvinceknight** [comment]
The landing page is just my opinion and I'm old and decreped so if all you kids love landing pages then that's the target audience (although I would suggest you ask what purpose it has). 

The disclaimer/official look is something to talk about: I mainly want to avoid a student making a choice based on bad/old data and it being the fault of the tool and that someone gets the blame.

**Comment by drvinceknight** [comment]
> I mainly want to avoid a student making a choice based on bad/old data and it being the fault of the tooltool.

I'm hoping/confident that we'll go through the relevant bureaucratic hoops and the School will populate the db so it won't be an issue :) This is a fantastic tool you've built and it's going to be very useful. It's awesome :+1:

**Comment by AdamPohl** [comment]
> we'll go through the relevant bureaucratic hoops

LOOOL. This was the hope I had as well.

> This is a fantastic tool you've built and it's going to be very useful.

I am glad you think so @drvinceknight, it may have taken three years but me and @alcarney have finally written code together that actually works. _YAY!!!_ (I am ignoring the code club website as that is a group effort) :+1: :smiling_imp:

**Comment by AdamPohl** [comment]
@drvinceknight @alcarney I have changed the pics what do you guys think of this?

**Comment by drvinceknight** [comment]
> @drvinceknight @alcarney I have changed the pics what do you guys think of this?

I like it better :)

**Comment by AdamPohl** [comment]
@drvinceknight Cool cool :imp:

**Pull request merged**
