### PR TITLE
Adding kwalify tests

### PR DESCRIPTION
**Pull request by alcarney**
- The structure of the yaml data had to be tweaked slightly so that it
  was testasble
- This has caused a slight increase to the complexity of the templates
  but in my opinion the trade off is worth it
- The tests currently test the _structure_ of the data but not if it
  makes sense, those will have to be done at a later point
- The tests are carried out _before_ the site is built so if the data
  doesn't make sense the site will refuse to build
- This should affect the user's view of the site at all

### CODE REVIEW

**Comment by AdamPohl** [comment]
Travis hasn't run, commit again

**Comment by alcarney** [comment]
@Huaraz2 Have you enabled Travis for the new repository?

**Comment by AdamPohl** [comment]
@alcarney It is now linked so please commit again and if it passes I will pull it in

**Comment by AdamPohl** [comment]
@alcarney Travis is failing to load html-proofer again

**Comment by alcarney** [comment]
@Huaraz2 I think I have finally figured out the tests

**Comment by AdamPohl** [comment]
@alcarney That's always good. :p

**Pull request merged**
